version: "3.5"

services:
  wtm:
    container_name: WTM
    image: wtm:latest
    restart: always
    build:
      context: .
      target: aiohttp-backend
    volumes:
      - ./config.toml:/app/config.toml:ro
    ports:
      - 5530:8080
