version: "3.5"

services:
  wtm:
    container_name: WTM
    image: ghcr.io/devteshin/wtm:{TAG:-latest}
    restart: always
    volumes:
      - ./config.toml:/app/config.toml:ro
    ports:
      - ${EXPOSE_PORT:-5530}:8080
